"""initial

Revision ID: 8cc0f9c8e920
Revises: 
Create Date: 2022-03-26 16:49:51.766980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc0f9c8e920'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avg_temphumi',
    sa.Column('day', sa.String(length=64), nullable=False),
    sa.Column('avg_temp', sa.Float(), nullable=True),
    sa.Column('avg_humi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('failed_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('not_registered_user', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targettemp',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('target_temp', sa.Integer(), nullable=True),
    sa.Column('by_who', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('temphumi',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('humi', sa.Float(), nullable=True),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('temphumi')
    op.drop_table('targettemp')
    op.drop_table('failed_login')
    op.drop_table('avg_temphumi')
    # ### end Alembic commands ###
